version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - weaviate
    environment:
      - API_KEY=${API_KEY}
      - WEAVIATE_URL=http://weaviate:8080
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
  weaviate:
    image: semitechnologies/weaviate:1.20.0
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
  celery:
    build: .
    command: celery -A app.tasks.celery_tasks worker --loglevel=info
    depends_on:
      - redis
    environment:
      - API_KEY=${API_KEY}
      - WEAVIATE_URL=http://weaviate:8080
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0